### ISSUE TITLE
Implantation of strictlynested = false is something wrong

### ISSUE THREAD

**Issue by shinaoka** [tensor4all/TensorCrossInterpolation.jl#1]
The implementation may need to be corrected.
The correct one is that before each half sweep, back up all I and J sets and add them to Pi tensors during the half sweep. 
https://github.com/tensor4all/TensorCrossInterpolation.jl/blob/main/src/tensorci2.jl#L787-L799

**Comment by rittermarc** [comment]
Agreed. That part of the code has to be inside the loop.
