### ISSUE TITLE
Difference between tolerance/pivottolerance in tensorci2.jl

### ISSUE THREAD

**Issue by RaimelMedina** [tensor4all/TensorCrossInterpolation.jl#35]
Hi guys!

First, thank you very much for such a nice library and work!!

Recently, with a colleague we were looking at tensorci2 and realized that perhaps tolerance is not being used. In the `optimize!` function you have both tolerance and pivottolerance
```
function optimize!(
    tci::TensorCI2{ValueType},
    f;
    tolerance::Float64=1e-8,
    pivottolerance::Float64=tolerance,
    maxbonddim::Int=typemax(Int),
    maxiter::Int=20,
    sweepstrategy::Symbol=:backandforth,
    pivotsearch::Symbol=:full,
    verbosity::Int=0,
    loginterval::Int=10,
    normalizeerror::Bool=true,
    ncheckhistory::Int=3,
    maxnglobalpivot::Int=5,
    nsearchglobalpivot::Int=5,
    tolmarginglobalsearch::Float64=10.0,
    strictlynested::Bool=false,
    checkbatchevaluatable::Bool=false
) where {ValueType}
```
However, inside the function tolerance is never used and only pivottolerance is (through `abstol = pivottolerance * errornormalization;`). 

I tested the code with different values of tolerance (1e-6, 1e-2, 1.0) and the same pivottolerance and the results were the same. Is this expected?

Thanks!

**Comment by shinaoka** [comment]
Thank you for the report. This may be a bug.
If we pass `pivottolerance` explicitly to `optimize!`, `tolerance` will not be used.

We intended that `tolerance` is a main parameter and `pivot tolerance` is optional.

We will discuss it internally and may change the interface. In the meanwhile, could you use `tolerance` and avoid using `pivottolerance`?

**Comment by RaimelMedina** [comment]
Thanks for the quick reply. I will keep using it as before in the meantime :) 
Thanks once again

**Comment by shinaoka** [comment]
@rittermarc 
What do you think? If you are not using `pivottolerance`, we could consider to remove it.

**Comment by RaimelMedina** [comment]
Thanks to you guys for the amazing job!!!!
